version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:3.8.7'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
  test:
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          nosetests tests/math-test.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
